### ISSUE TITLE
CBreadcrumbSeparator not visible by default

### ISSUE THREAD

**Issue by codebender828** [chakra-ui/chakra-ui-vue#111]
**Describe the bug**
The `CBreadcrumbSeparator` is not rendered in between multiple `CBreadcrumbItem`.
### How to reproduce
**Code: **
```vue
<CBreadcrumb :add-separator="false">
  <CBreadcrumbItem>
    <CBreadcrumbLink href="#">Breadcrumb 1</CBreadcrumbLink>
  </CBreadcrumbItem>
  <CBreadcrumbItem>
    <CBreadcrumbLink href="#">Breadcrumb 2</CBreadcrumbLink>
  </CBreadcrumbItem>
  <CBreadcrumbItem isCurrentPage>
    <CBreadcrumbLink href="#">Breadcrumb 2</CBreadcrumbLink>
  </CBreadcrumbItem>
</CBreadcrumb>
```
**Output**
![image](https://user-images.githubusercontent.com/21237954/78709233-ec287480-7945-11ea-8eee-e73e2fab0933.png)

### Expected behavior
The `CBreadcrumbSeparator` should be rendered in between multiple `CBreadcrumbItem`s by default. When the `is-current-page` prop is passed the corresponding item separator should be hidden.

**Desired Output**
![image](https://user-images.githubusercontent.com/21237954/78709438-3d386880-7946-11ea-916e-64aa2e7d5dc7.png)

**Comment by koca** [comment]
I think it works as expected. 
You set `:add-separator` to false. If you want to add seperators manually then you need to add `CBreadcrumbSeparator` component too.

Like so:
```diff
<CBreadcrumb :add-separator="false">
  <CBreadcrumbItem>
    <CBreadcrumbLink href="#">Breadcrumb 1</CBreadcrumbLink>
+   <BreadcrumbSeparator color="red.500" fontSize="20px" />
  </CBreadcrumbItem>
  <CBreadcrumbItem>
    <CBreadcrumbLink href="#">Breadcrumb 2</CBreadcrumbLink>
+   <BreadcrumbSeparator color="red.500" fontSize="20px" />
  </CBreadcrumbItem>
  <CBreadcrumbItem isCurrentPage>
    <CBreadcrumbLink href="#">Breadcrumb 2</CBreadcrumbLink>
  </CBreadcrumbItem>
</CBreadcrumb>
```

**Comment by codebender828** [comment]
Haha thanks. I realised as well this morning. I guess my brain was tired last night 😄
