### ISSUE TITLE
Closing Modal also closes open Drawer Component

### ISSUE THREAD

**Issue by sibeshkar** [chakra-ui/chakra-ui-vue#122]
**Describe the bug**
On triggering `onClose` for a hovering Modal triggered from a Drawer component, the Drawer component closes too.

**To Reproduce**
1. Add Drawer component
2. Add a button with Modal trigger to Drawer component
3. Open Drawer component and click button to open the Modal
4. Close the Modal and Drawer component also closes

**Expected behavior**
Only the Modal should close and the Drawer should remain open.

**Desktop (please complete the following information):**
 - OS: Mac OS X
 - Browser : Brave Browser
 - Version : 1.13.113

Thanks!

**Comment by codebender828** [comment]
Hey @sibeshkar ! Thanks for catching this bug. Could you kindly share a link to codesandbox of the bug?

**Comment by sibeshkar** [comment]
Sorry, seem to have opened this on the Vue.js version. Reopened it on the React version https://github.com/chakra-ui/chakra-ui/issues/614
