### ISSUE TITLE
[DOCS]: Add CCollapse component easing props to docs

### ISSUE THREAD

**Issue by codebender828** [chakra-ui/chakra-ui-vue#144]
**Is your feature request related to a problem? Please describe.**
Add the easing function values for the `enterEasing` and `leaveEasing` props for the `CCollapse` component documentation.

Easing documentation -> https://chakra-ui-vue.now.sh/collapse

The `CCollapse` component uses [animejs](https://animejs.com/documentation/#linearEasing), so it accepts the animejs easing props.

__Might be related to Issue #69 .__

If you wish to own this issue feel free to take this and open a PR against #69.

**Comment by peoray** [comment]
I'd like to pick this up.

@codebender828 Can you provide more context, please?
