### ISSUE TITLE
Implement v-model on CNumberInput component

### ISSUE THREAD

**Issue by codebender828** [chakra-ui/chakra-ui-vue#150]
**Is your feature request related to a problem? Please describe.**
The number input doesn't have a 2 way binding implmentation.

**Describe the solution you'd like**
Implement v-model on CNumberInput

**Comment by peoray** [comment]
I'd like to work on this ;)

**Comment by codebender828** [comment]
Hey Peoray! Thanks for the help with this! Coolio. Feel free to fork it and open a PR!

My target is for us to launch v1 on hopefully on Saturday!

**Comment by codebender828** [comment]
Hey @peoray ! Thanks for taking this on. 

Feel free to fork the repo and work on it. There's a contribution guide on the readme to help you get started with development.

Let me know here or on the discord chat!

https://discord.gg/7ZNcDv

**Comment by peoray** [comment]
@codebender828, I'd like more context about the issue. Going through the files, I'm confused as to which file I'm supposed to edit.

**Comment by codebender828** [comment]
The file to edit is the `CNumberInput.js` file. Currently it has a `defaultValue` prop which technically should not be there. In order to implement `v-model` you need to:
1. Add a `model` option the component.
  a. Set the event to emit to update the prop. 
  b. Set the prop the relay the internal state for the `CNumberInput.

2. On every change of the value of the input element, you emit the event specified in the `model` option.

You can see the `CInput` component for an example of this implementation.
