### ISSUE TITLE
Add v-model implementation for CSlider

### ISSUE THREAD

**Issue by codebender828** [chakra-ui/chakra-ui-vue#151]
**Is your feature request related to a problem? Please describe.**
Currently the slider doesn't have a 2 way binding implementation

**Describe the solution you'd like**
Implement v-model for the CSlider component

**Comment by peoray** [comment]
Picking this up as well :)

**Comment by peoray** [comment]
I guess this is very similar to the `Numberinput`, should be `change` instead of `input` and this is already being emitted in the `updateValue` method?

I need your thoughts on this ;)

**Comment by codebender828** [comment]
> I guess this is very similar to the Numberinput, should be change instead of input and this is already being emitted in the updateValue method?

Spot on, @peoray
