### ISSUE TITLE
[Bug]: Tab can be disabled and also could be set as the default tab

### ISSUE THREAD

**Issue by DominusKelvin** [chakra-ui/chakra-ui-vue#163]
**Describe the bug**
A tab that is disabled can also be said as the default tab with `defaultIndex`

**To Reproduce**
1. Create 3 tabs
2. Set the `defaultIndex`  props on tabs to the third tab via `:default-index="2"`
3. Disable the third tab by passing it the `is-disabled` prop

**Expected behavior**
I suppose Chakra UI Vue should complain or default to the first tab on the list of tabs instead of both disabling the third tab and also showing it's content.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Pop!_OS
 - Browser chrome
 - Version 81.0.4044.129 (Official Build) (64-bit)

**Comment by codebender828** [comment]
Thanks for opening this issue, @DominusKelvin 

I think this is still okay since it's the user that sets the default tab. I think this would be a problem if a disabled tab can be activated.

So for now this is will not be fixed.
