### ISSUE TITLE
NaN in NumberInput when min/max value is exceeded

### ISSUE THREAD

**Issue by gustojs** [chakra-ui/chakra-ui-vue#178]
**Describe the bug**
NumberInput field shows NaN and loses functionality when the min/max value limit is exceeded.

**To Reproduce**
1. Go to https://vue.chakra-ui.com/numberinput
2. Focus on input with min/max value
3. Press 0, so that value is 150
4. See NaN
5. Enter 15 again
6. Try to press up or down - doesn't work anymore

**Expected behavior**
Not sure tbh. I'd probably expect the value to stay at 15.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox
 - Version 76.0

**Comment by codebender828** [comment]
Noted! Thanks for catching this! Will look into this and try to fix it ASAP.

**Comment by codebender828** [comment]
Hi @gustojs  ! This issue was fixed in the recent patch. You can upgrade to v@0.5.1 to see the changes! Thank you!
