### ISSUE TITLE
Popover's CPopperArrow rotation resets on-update

### ISSUE THREAD

**Issue by xewl** [chakra-ui/chakra-ui-vue#183]
**Describe the bug**
The arrow in the Popover component looses its 45° rotation on-update.
The `CPopperArrow` component initially has styles:
`position: absolute; transform: translate(152px, 0px) rotate(45deg); left: 0px;`
which becomes:
`position: absolute; transform: translate(152px, 0px); left: 0px;`

**To Reproduce**
1. Go to 'https://vue.chakra-ui.com/popover'
2. Click on any 'trigger'
3. Scroll or resize window
4. See arrow become square

**Expected behavior**
The arrow keeping its triangle formation / its 45° rotation.

**Screenshots**
![chakrauibug](https://user-images.githubusercontent.com/245041/81488550-855ee980-926a-11ea-947d-27ea3b50ae54.gif)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome 81.0.4044.138 / Firefox 74.0 & 76.0.1 (x64)
**Smartphone (please complete the following information):**
(Not a browser/OS related matter)

**Comment by codebender828** [comment]
I recently upgraded Popover to use V2. I think perhaps that's where this came from. I believe it  might need some style re-ordering. Thanks, @xewl !

**Comment by codebender828** [comment]
Hi @xewl ! This issue was fixed in the recent patch. You can upgrade to v@0.5.1 to see the changes! Thank you!
