### ISSUE TITLE
Bug: NumberInput ids are created at build time and not at component initialization time

### ISSUE THREAD

**Issue by codebender828** [chakra-ui/chakra-ui-vue#184]
**Describe the bug**
CNumberInput component ids are created at build time and not at component initialization time.

This results in duplication

**To Reproduce**
1. Go to https://vue.chakra-ui.com/numberinput
2. Open dev tools.
4. See id's warning in console

**Expected behavior**
Id's should be generated only when the component is created.

**Screenshots**
![image](https://user-images.githubusercontent.com/21237954/81493585-06060000-92d4-11ea-92fe-99668c238cc1.png)

Can be fixed be moving id generation to a computed property.

**Comment by peoray** [comment]
Picking this up if it's still up.

So I'm a little bit confused.`id generation` is done by the `useId` function in `utils`. Either that or as a `inputId` prop passed by the user. What exactly do you mean by moving id generation to computed property?

**Comment by codebender828** [comment]
Currently there's an `id` prop that has a default. 

The problem is that since this function is called at build time, and not at component instantiation time, this can result in the same value each time time the the component is used in the template. 

To solve this we need to move that function call to the computer property. You can see this in the RadioGroup component.

https://github.com/chakra-ui/chakra-ui-vue/blob/02a4c5f6c3afc0c7a93721b0021b561a9c7035d1/packages/chakra-ui-core/src/CRadioGroup/CRadioGroup.js#L34

**Comment by peoray** [comment]
Might probably sound silly but isn't the `_inputId` already a computed property or is there something I'm missing?

**Comment by codebender828** [comment]
Hey @peoray ! Sorry for my late response. I haven't looked at this thread since yesterday.

Just looked at the file. Yes, you're right. we can use the `_inputId` variable It can be fixed by removing the `default` property on the `inputId` prop. That's what's causing the id duplication.
