### ISSUE TITLE
[Docs] Contributors link is broken

### ISSUE THREAD

**Issue by guastallaigor** [chakra-ui/chakra-ui-vue#189]
**Describe the bug**

The contributors link is broken in the footer of the vue.chakra-ui.com page.

**To Reproduce**
1. Go to https://vue.chakra-ui.com/
2. Scroll down to the footer
3. Click on the contributors link
4. See 404 Not found page

**Expected behavior**
Go to a contributors page or the Github contributors [graph](https://github.com/chakra-ui/chakra-ui-vue/graphs/contributors)

**Screenshots**

![image](https://user-images.githubusercontent.com/22016005/81502100-448ac300-92b2-11ea-9229-97bcbc399216.png)

![image](https://user-images.githubusercontent.com/22016005/81502104-4bb1d100-92b2-11ea-8b3b-8ee298ee8888.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 81.0.4044.138 (Official Build) (64-bit) 

**Smartphone (please complete the following information):**

**Additional context**
Also, I think the Contributors anchor is not working in the Github `README.md` as well.

**Comment by codebender828** [comment]
Thanks for catching that @guastallaigor . Didn't spot it. Will look into it.

**Comment by codebender828** [comment]
Haha accidentally pressed close. 😂

**Comment by peoray** [comment]
Seems this issue is fixed, although I didn't see any PR. Works for me, probably close this to avoid confusion :)

**Comment by codebender828** [comment]
I don't think it is yet. It breaks on initial request. You can try doing a hard refresh on the contributors page. To see this.

The reason is because this page is not statically generate during deployment.

 This can be fixed by adding  the 'Contributors' to the `all-routes.js` file.

**Comment by peoray** [comment]
Got you. That's the file in the `utils` folder in the docs directory?
Considering how that is arranged, where would be appropriate to include the `Contributors`?
