### ISSUE TITLE
Chakra Plugin Types for autocomplete

### ISSUE THREAD

**Issue by codebender828** [chakra-ui/chakra-ui-vue#202]
**Is your feature request related to a problem? Please describe.**
Users might need their editors to suggest possible plugin options for Chakr aUI when registering the Chakra plugin.

**Describe the solution you'd like**
Create type declaration files for the Chakra plugin to suggest these options for autocomplete.

**Describe alternatives you've considered**
JSDocs. The problem with this is that it implies that every user uses VSCode and has the JSDocs extension installed which will not always be the case.

**Additional context**
This can be added to the `@charka-ui/vue` package and added in the `dist/types` directory after the final build.

See the `Chakra/index.js` file for JSDoc context.

**Comment by DominusKelvin** [comment]
@codebender828 I'd take this up.

**Comment by codebender828** [comment]
Closed in #380
