### ISSUE TITLE
[Docs] Add links between React and Vue websites

### ISSUE THREAD

**Issue by gustojs** [chakra-ui/chakra-ui-vue#207]
**Is your feature request related to a problem? Please describe.**
Right now, when I google Chakra and open the React version, I can't switch to Vue. Same the other way.

**Describe the solution you'd like**
I'd like them to be linked together.

**Comment by lauragift21** [comment]
Hey, @codebender828 if you need help here happy to take this on :)

**Comment by codebender828** [comment]
Hello @lauragift21 ! Thanks for taking this on! I'll assign this to you then! Here's how to get started with setup!

https://vue.chakra-ui.com/contributing#docs-contribution

After cloning the repo and creating a branch, you can do this:

```bash
yarn bootstrap # Installs and links packages
yarn build # Builds packages
yarn docs:dev # Starts docs dev server
```

If you have any issues, feel free to join the team's discord!
https://discord.gg/3F5ets

**Comment by lauragift21** [comment]
Hey @codebender828 what do you think about these options for where to place the link to React site? 
<img width="1440" alt="Screenshot 2020-06-01 at 2 50 30 PM" src="https://user-images.githubusercontent.com/17781315/83415762-89b89580-a417-11ea-8446-4dfd7f2eb706.png">
<img width="1438" alt="Screenshot 2020-06-01 at 2 50 43 PM" src="https://user-images.githubusercontent.com/17781315/83415767-8cb38600-a417-11ea-8668-70445d5739e9.png">
<img width="1438" alt="Screenshot 2020-06-01 at 2 52 23 PM" src="https://user-images.githubusercontent.com/17781315/83415770-8d4c1c80-a417-11ea-8b2d-165f3fed0898.png">

**Comment by peoray** [comment]
I prefer the first one :)
