### ISSUE TITLE
Cannot find module '@chakra-ui/vue'

### ISSUE THREAD

**Issue by pabueco** [chakra-ui/chakra-ui-vue#210]
**Describe the bug**
When using one of the latest versions (I tested 0.5.6 and 0.5.7) the module is not found. When checking the node_modules folder you can see, that the `dist` folder is missing. Only a `src` folder exists. So the main script (`dist/cjs/index.js`) does not exist.
Version 0.5.3 works.

**To Reproduce**
1. Install one of the latest versions (0.5.6 or 0.5.7)
2. Import anything from the module

**Additional context**
I tried it with Laravel Mix (v5) and Vue CLI 4.

**Comment by codebender828** [comment]
Hey @pabueco ! Thanks for catching this. Let me look into this.

**Comment by codebender828** [comment]
Hey @pabueco !

Kindly install the latest version, `@0.5.9`! I've been trying to auto mate the CI process so there were a few hiccups. There's not many big API changes. Just internal optimizations from `@0.5.3` that help improve component performance. Let me know if you have any issues!
