### ISSUE TITLE
Add a next or previous link at the bottom of the page

### ISSUE THREAD

**Issue by peoray** [chakra-ui/chakra-ui-vue#211]
**Is your feature request related to a problem? Please describe.**

I'm reading through the docs and I noticed there is no `next`  or `previous` link at the bottom of the page. I had to scroll back up to the section on the sidebar where the page I want to move to is. I believe this is bad for user experience.

Is this intentional or something we might want to work on?

**Describe the solution you'd like**
A `link` or `button` with either a text/symbol or both that illustrates previous or next sections to the user.

**Comment by codebender828** [comment]
Hey @peoray . This was initially not something I had prioritized. But you're right. It can be good for ux. 

We can create a component to do this. If you're interested in taking this on now, you can use the `$router.options.routes` option to get all the list of routes.

You can then use this array of routes to compare next and previous links

**Comment by Easybuoy** [comment]
I'd like to take this on @codebender828

**Comment by peoray** [comment]
@Easybuoy sure :). If you need help, do not hestitate to reach out

**Comment by Easybuoy** [comment]
I'm having a bit of a problem with this, the links are jumping around because they're arranged alphabetically and not according to how they're represented on the side navigation.
