### ISSUE TITLE
[Docs]: Add search for documentation

### ISSUE THREAD

**Issue by codebender828** [chakra-ui/chakra-ui-vue#217]
**Is your feature request related to a problem? Please describe.**
This feature would introduce search for the documentation site for Chakra UI Vue. This will allow easier navigation.

**Describe the solution you'd like**
Use [Algolia](https://www.algolia.com/) for search.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by peoray** [comment]
Signalling interest in this one. Willing to assist someone who knows what they are doing :grin:

**Comment by codebender828** [comment]
If you want to take the lead on this I can assign this to you. It's actually relatively simple. DM me your email on discord so I can copy you in on the emails between the Algolia team and myself.

https://docsearch.algolia.com/

The supposedly handle all the indexing for us. We just need to include a snippet. There are some other things that can be done to improve search here:

https://docsearch.algolia.com/docs/tips/

**Comment by peoray** [comment]
Gone through the docs. Algolia indexes the pages every 24hrs. 
Did you apply already?

**Comment by codebender828** [comment]
Yes. I already did. They said they'll send us the snippet in the email thread.

**Comment by codebender828** [comment]
Done in #258
