### ISSUE TITLE
[CHORE]: Deprecate vue-cli-service ESLint & use base ESLint.

### ISSUE THREAD

**Issue by codebender828** [chakra-ui/chakra-ui-vue#219]
**Is your feature request related to a problem? Please describe.**
This project was originally built with Vue CLI 3 and has transitioned into a monorepo with lerna and yarn workspaces.

The challenge is that different packages end up having different ESLint configs. I'd like for these to be unified into one so contributors are able to contribute comfortable without insecurities about linting.

**Describe the solution you'd like**
1. Figure out how to setup ESLint config that we can execute from the root in specific/all packages.
2. Extend [`@nuxt/eslint-config`](https://github.com/nuxt/eslint-config). I feel this config fits nicely between pure Javascript modules and Vue components.

**Comment by Easybuoy** [comment]
Hi @codebender828, I can work on this.

**Comment by codebender828** [comment]
Hi, @Easybuoy . Great. Thanks for taking this on. I'll go ahead and assign this to you. Let me know if you have any problems. You can join the [team discord](https://discord.gg/Fu44Db) for quicker responses.
