### ISSUE TITLE
[CLI Tooling]: Add support for `create-nuxt-app`

### ISSUE THREAD

**Issue by codebender828** [chakra-ui/chakra-ui-vue#226]
**Is your feature request related to a problem? Please describe.**
To make it simple for users to get started with Chakra UI Vue with Nuxt.js, we can include `Chakra UI Vue` as an option to the CLI template.

**Describe the solution you'd like**
Add Chakra UI Vue as an option to `create-nuxt-app`.

**Additional Context**
Should be added at the Create Nuxt App repo.

See:
https://github.com/nuxt/create-nuxt-app/tree/master/packages/cna-template/template/frameworks

**Comment by Easybuoy** [comment]
I can attempt this @codebender828 :)

**Comment by Easybuoy** [comment]
Would we have a page that the user sees after installing `chakra-ui-vue` as their UI framework? 
@codebender828

**Comment by codebender828** [comment]
Yeah that's a good idea. I think other frameworks do have one. You can use the Nuxt Starter as a Template. You can get the link to the Codesandbox on the docs

**Comment by codebender828** [comment]
Hey @Easybuoy ! How are you? Any progress with this? I can take it on if you feel you can't work on this right now.

**Comment by Easybuoy** [comment]
Hi @codebender828, I'm great. I ran into an issue creating the starter template with `chakra-ui-vue`. I must have lost track of this task. I'd look into it again, and let you know if I'm still having that issue.

**Comment by codebender828** [comment]
Cheers. Sure thing. Let me know if you have any issues 👍

**Comment by Easybuoy** [comment]
It's fine if I use the same content with the Nuxtcode sandbox starter for `chakra-ui-vue` right? @codebender828 

This one https://codesandbox.io/s/chakra-ui-nuxt-demo-f8tq4

**Comment by Easybuoy** [comment]
Pull request raised https://github.com/nuxt/create-nuxt-app/pull/573

**Comment by Easybuoy** [comment]
Pull request raised @codebender828 https://github.com/nuxt/create-nuxt-app/pull/573

**Comment by codebender828** [comment]
Thanks @Easybuoy ! Reviewed the PR. Requested a few changes

**Comment by Easybuoy** [comment]
It's been merged @codebender828 🎉

**Comment by codebender828** [comment]
Awesome! Let's test it out! Thank you for working on this!

**Comment by codebender828** [comment]
Was just poking around with this, and I realized that it doesn't install the latest version of `@chakra-ui/vue`. I think it only installs the version that was active at the time of us working on the CLI tool. 

The current version of Chakra UI Vue is at `0.6.0` and but the installed version is at `0.5.11`. See image below for reference.

![Screen Shot 2020-07-28 at 11 37 30 AM](https://user-images.githubusercontent.com/21237954/88616552-06d65300-d0c7-11ea-9800-97d820caaa77.png)

How does `create-nuxt-app` handle the latest versions of frameworks?

**Comment by Easybuoy** [comment]
So I think this might have to do with how `@chakra-ui/nuxt` installs the `@chakra-ui/vue` dependency.

Find the version that was specified for `create-nuxt-app` below
```
{
  "dependencies": {
    "@chakra-ui/nuxt": "^0.0.7",
    "@nuxtjs/emotion": "^0.0.1"
  }
}
```

**Comment by Easybuoy** [comment]
So I think this might have to do with how `@chakra-ui/nuxt` installs the `@chakra-ui/vue` dependency.

Find the version that was specified for `create-nuxt-app` below @codebender828 
```
{
  "dependencies": {
    "@chakra-ui/nuxt": "^0.0.7",
    "@nuxtjs/emotion": "^0.0.1"
  }
}
```

**Comment by codebender828** [comment]
Understood. I think I have some ideas to update the module before finally closing this. 👍🏽

**Comment by Easybuoy** [comment]
Okay, I'm down to help with it if you want

**Comment by Easybuoy** [comment]
Okay, I'm down to help with it

**Comment by codebender828** [comment]
I think for every version we release of the module we need to update the `cna-template` in Create Nuxt App for Chakra UI from the looks of it. I juts published the latest version of `@chakra-ui/nuxt` which is [`v0.0.8`](https://www.npmjs.com/package/@chakra-ui/nuxt). It installs the latest version of `@chakra-ui/vue`. I think we need to open another PR to CNA.

Also I think there should be a better system for this to manage versioning between the module and `create-nuxt-app`. Do you have any ideas?

**Comment by Easybuoy** [comment]
I thought the idea of using versions like `^0.0.7` is that it installs any update till the package gets to a major release. 

I did some reading, it would have been fine if the version of `@chakra-ui/nuxt` is greater than `1.0.0`, so we would not have to update it until it gets to a major release like `2.0.0`.

 So for now, it seems we would have to update it manually until we get to version `1.x.x`.

Find some of the resources I read below:
https://stackoverflow.com/questions/34997079/npm-install-with-caret-semver-not-getting-version-updates
https://docs.npmjs.com/misc/semver#caret-ranges-123-025-004

I would raise a PR to update the version in Create Nuxt App.

**Comment by Easybuoy** [comment]
So I think `create-nuxt-app` has a bot that updates the dependencies regularly, so we wouldn't have to be creating pull requests for them manually @codebender828 . 

See example [here](https://github.com/nuxt/create-nuxt-app/pull/580)

**Comment by codebender828** [comment]
Oh, that's interesting. I saw that the PR has updated with the most recent dependency updates so that's good. So do we just need to wait until it's merged?

**Comment by Easybuoy** [comment]
Yes, we need to wait until it's merged

**Comment by codebender828** [comment]
Noted. Then I think we can close it 👍🏽
