### ISSUE TITLE
[Feature]: Improve styling escape hatches for styles overide.

### ISSUE THREAD

**Issue by codebender828** [chakra-ui/chakra-ui-vue#230]
**Is your feature request related to a problem? Please describe.**
Currently in Chakra UI Vue, in order to apply a manual object of styles in the template as an escape hatch, you need to create the object in the template and and then bind the class to the element in the template.

This seems to work fine. However, after using this for a while, it seems quite verbose.

**Describe the solution you'd like**

I'd like to propose a better escape hatch, which would include using a `v-chakra` directive that accepts an object of styles and binds the class name to the element.

e.g.:
Basic usage 1: (Object of styles)
```vue
<div v-chakra="{ bg: 'tomato', color: 'white', p: 3 }" >I am happy div</div>
```

Advanced usage 2: (Function that accepts theme & color mode)
```vue
<template>
  <div v-chakra="useStyles" >I am happy div</div>
</template>

<script>
export default {
  computed: {
    useStyles: vm => (theme, colorMode) => { /* object of styles */ }
  }
}
</script>
```

**Pros:**
- Gives any basic HTML element the ability to be styled with using Chakra UI Vue.
- Can be extended to read attributes so as to bind styles via attributes. e.g.

```vue
<button v-chakra p="3" bg="blue.400" d="flex">
  Click Me
</button>
```
This allows non-chakra components to benefit from Chakra's constraint based design patterns.

**Additional context**
- Need to do some research around how this would work with Nuxt.js

**Comment by codebender828** [comment]
Happy to gather some feedback around this.

**Comment by koca** [comment]
Hey @codebender828!

API looks good to me: 

```html
<div v-chakra="{ bg: 'tomato', color: 'white', p: 3 }" >I am happy div</div>
```

```html
<button v-chakra p="3" bg="blue.400" d="flex">
```

Recently I was also thinking about integrating the `sx` prop from Theme UI. https://theme-ui.com/sx-prop/

The `sx` api is similar to `v-chakra="{}"` but it's more powerful than that. I'm sure you already know that. 

**Example 1:** With `sx` we can support the basics:
```html
<div sx="{ bg: 'tomato', color: 'white', p: 3 }" >I am happy div</div>
```
**Example 2:** And the advanced stuff (this would be useful for 3rd party components etc)
(I kinda need this all the time 😄 )
```html
<div sx="{
      h1: {
        bg: 'blue.400'
      },
      '& > div': {
        fontSize: [2, 3, 4]
      },
      '@media screen and (min-width: 40em)': {
        width: '50%',
      }
    }">
  <h1>Title</h1>
  <p>Text</p>
</div>
```


So... What do you think?

**Comment by codebender828** [comment]
Thanks, @koca ! Interesting. This escape hatch would also provide the same functionality as the `sx` prop. In our case we would replace `sx` with the `v-chakra` directive. So you can write actual CSS if you want to. 👍🏽

```vue
<div v-chakra="{
      p: 3,
      boxShadow: theme => `0 0 4px ${theme.colors.primary}`,
      h1: {
        bg: 'blue.400'
      },
      '& > div': {
        fontSize: [2, 3, 4]
      },
      '@media screen and (min-width: 40em)': {
        width: '50%',
      },
      
    }">
  <h1>Title</h1>
  <p>Text</p>
</div>
```

**Comment by koca** [comment]
> Actually it would be shorter since the values passed would inherently have access to the theme object via styled system. So in case you need to use `theme.colors.primary` you wouldn't need to provide a function that gives the theme. You'd just reference the color you want to access.(Theoretically)
> 
> But we can still provide the function as well if you wish. :D

I know but its for advanced use cases where you need power of js say you want to darken the color using a color package or something etc. 

```html
<div v-chakra="{
      boxShadow: theme => `0 0 4px ${ darken(theme.blue.400, 10) }`,
    }">
</div>
```
