### ISSUE TITLE
[Docs]: Change logo text to vector path

### ISSUE THREAD

**Issue by jbienesdev** [chakra-ui/chakra-ui-vue#236]
**Describe the bug**
The logo text (`chakra`) looks off when I view it on browser/mobile phone. `Inter` font needs to be installed in the system to view the font correctly.

**Expected behavior**
Logo text should be rendered correctly on any device without installing the font.

**Screenshots**
`Inter` font is not installed in the system:
![image](https://user-images.githubusercontent.com/17470909/84080483-d18a7e80-aa0e-11ea-83ce-3bbad0ae7abd.png)

`Inter` font is installed in the system (still looks off though):
![image](https://user-images.githubusercontent.com/17470909/84080578-f7178800-aa0e-11ea-8b89-377e23375d65.png)

**Desktop (please complete the following information):**
 - OS: MacOS Mojave
 - Browser Chrome
 - Version 83

**Additional context**
To fix this, the logo text needs to be converted to vector paths (outlines) using any vector graphics editor.

I already prepared a fix for this, this is what I came up to. Let me know so that I can create a PR for this issue.

`Light mode`
![image](https://user-images.githubusercontent.com/17470909/84081113-f3383580-aa0f-11ea-9284-1c7aa5bd3b7c.png)

`Dark mode`
![image](https://user-images.githubusercontent.com/17470909/84081154-064b0580-aa10-11ea-8bf9-967cedf57fea.png)

**Comment by codebender828** [comment]
Thanks @jbienesdev for this! Go ahead with the PR.🎉
The logo was honestly built on the fly so happy to see it improved!

**Comment by jbienesdev** [comment]
Cool! @codebender828 I also noticed a typo on the front page. Can I include it with the PR?

`verison` -> `version`
![image](https://user-images.githubusercontent.com/17470909/84091970-a14fd980-aa28-11ea-802b-f9523c4908d5.png)

**Comment by codebender828** [comment]
Yes of course. Thank you, @jbienesdev . Nice catch!

**Comment by jbienesdev** [comment]
@codebender828 can you re-open this issue? I noticed a bug on the text color when you're accessing the documentation. It's just a one line fix.

## DEMO
![chakra](https://user-images.githubusercontent.com/17470909/84095392-c72dac00-aa31-11ea-8ff1-d7665077863f.gif)

**Comment by codebender828** [comment]
Yeah just noticed it as well. The React text should also inherit the parent colors. You can remove the color prop to see if that resolves it or you can make use of the color mode. 👍🏽

**Comment by jbienesdev** [comment]
Yeah. It's being overwritten with the style prop. Just gonna remove that one. Sorry about that.
