### ISSUE TITLE
Community: Add Chakra Discord Channel to Documentation Nav

### ISSUE THREAD

**Issue by codebender828** [chakra-ui/chakra-ui-vue#267]
**Is your feature request related to a problem? Please describe.**
In order give community members a place to discuss and get more interactive communications around solutions/problems/discussions in Chakra UI, a more asynchronous place is more suitable than issues.

**Describe the solution you'd like**
Open up Chakra Discord and include it in Docs Navbar

**Comment by codebender828** [comment]
@Anmol270900 Still want to take this on?

**Comment by Anmol270900** [comment]
Yes @codebender828 , on it!

**Comment by codebender828** [comment]
Let me know if you need any help with this. You can access me in Discord or on this thread.

**Comment by Anmol270900** [comment]
Hi @codebender828 , I ran into the error `Error: Cannot find module '@chakra-ui/vue'. Please verify that the package.json has a valid "main" entry  ` during initial setup. 
I have explained the whole thing in the Discord Vue Documentation channel.
Please have a look and guide on how to proceed.
Thankyou.
