### ISSUE TITLE
Modify default :focus color

### ISSUE THREAD

**Issue by JamesForan** [chakra-ui/chakra-ui-vue#273]
Hello!

I am Just getting started with Nuxt and Chakra UI, and am trying to work out how to modify a theme.

I am looking for an easy way to customize the :focus color across my theme.

I can see in the components.scss file that this is set to a default as follows:

  &::focus {
    box-shadow: 0 0 0 3px rgba(66, 153, 225, 0.6);
  }

What is the easiest way to set this in Nuxt?

Ideally, I would like to make this once, across all components.

I would also like the color to change with colorMode.

Thanks for your assistance.~

**Comment by codebender828** [comment]
Hey @JamesForan ! Greetings!

You can change the focus shadow styles by using the `extendTheme` option in your `nuxt.config.js` file. Since the focus style is a using the CSS `box-shadow` style, you need to modify the `shadows` key

Here's how to do it: 

```js
// nuxt.config.js

export default {
  chakra: {
    extendTheme: {
      shadows: {
        // You can also pass a value that you want here 👇🏽
        outline: '0 0 0 3px rgba(66, 153, 225, 0.6)'
      }
    }
  }
}
```

Let me know if this works for you 🙂

**Comment by codebender828** [comment]
Regarding changing the focus style using the current theme, sadly we don't have it yet, so you would have to manually add it to the components, or modify `this.$chakra.theme.shadows.outline` to the value you want depending on the current color mode 🤔. 

This however sounds like an interesting feature! 😀⚡Do you want to open a separate issue for it?

**Comment by JamesForan** [comment]
Hey Codebender!

Thanks for the quick reply. Setting the extendTheme did not work for me. however, directly setting this.$chakra.theme.shadows.outline did the trick.

I will try and have a look into why this is the case later on, but for now, I am happy!

Cheers,

James 👍🏻

**Comment by codebender828** [comment]
That's great! Oh I think I might know why you the `extendTheme` option didn't work for you. It's likely that you installed an old version of `@chakra-ui/nuxt` with `npx create-nuxt-app`. I recently published a fix that patches it up. Try upgrading your version of `@chakra-u/nuxt`. That should fix the theme extension option for you.

```bash
# Yarn
yarn add @chakra-ui/nuxt

# npm
npm install @chakra-ui/nuxt --save
```

Have you tried the new [`chakra-loader`](https://vue.chakra-ui.com/auto-import-components#with-nuxt.js) webpack plugin? If you didn't I thought I should also let you know about it to help improve your dev experience with Chakra UI Vue. It automatically will import and register for you only the Chakra components that you consume in the templates. So no need to manually import and register components. 😀❤️

Happy hacking and happy to help!

**Comment by JamesForan** [comment]
@codebender828 Thanks for this. I finally got the extended themes working.

I was having an issue with upgrading in Nuxt. I had to force it to go @latest.
`npm install @chakra-ui/nuxt@latest --save`

That upgraded to 0.0.9 and now extended themes is working.
