### ISSUE TITLE
Extended theme font family not being applied

### ISSUE THREAD

**Issue by dombavetta** [chakra-ui/chakra-ui-vue#274]
**Describe the bug**
Im attempting to extend the default theme by changing the font family used across the app. I looked through the source and noticed there were three font attributes "heading", "body" and "mono" that specified the font family to use within the components. I updated my my theme to override these values but it doesn't appear to take. See theme config below. Is this a misconfiguration on my part? I was basing this off of the theme file in source code.

![image](https://user-images.githubusercontent.com/33183744/89453474-f0fb0a80-d724-11ea-91a5-fe6568c5f8c3.png)

**To Reproduce**
1. Add `fonts` property to custom theme config, provide new font family values for `heading`, and `body`.
1. import custom theme config and assign to ` chakra { extendTheme: theme } ` in nuxt config
1. Inspect element created from a chakra component and observe its still using "-apple-system, BlinkMacSystemFont, etc.." for its font family.

**Expected behavior**
"IBM Plex Sans" takes over as the default font-family. If I apply the font family via style attribute directly on an element, it displays as expected.

**Screenshots**
![image](https://user-images.githubusercontent.com/33183744/89453288-a4173400-d724-11ea-8421-e6e5f06512c4.png)

**Desktop:**
 - OS: Mac OS 10.15.6
 - Browser Chrome
 - Version 84.0.4147.105 

**Additional context**
This is a nuxt v 2.14.0 application.

**Comment by codebender828** [comment]
Hi @dombavetta ! Sorry about the issue with the theme.

I recently published a fix for the theme merging problem in the latest version of `@chakra-ui/nuxt`.

Try running `yarn add @chakra-ui/nuxt` or with npm: `npm install @chakra-ui/nuxt`.

Let me know if this works for you ♥️🙏🏽

**Comment by dombavetta** [comment]
@codebender828 I was on v0.0.7 - that did the trick, thank you!
