### ISSUE TITLE
@chakra-ui/vue not bundled with type definition files

### ISSUE THREAD

**Issue by DanielAlongE** [chakra-ui/chakra-ui-vue#275]
**Describe the bug**
Could not find a declaration file for module '@chakra-ui/vue'. 'c:/Projects/bible-pwa/node_modules/@chakra-ui/vue/dist/cjs/index.js' implicitly has an 'any' type.
  Try `npm install @types/chakra-ui__vue` if it exists or add a new declaration (.d.ts) file containing `declare module '@chakra-ui/vue';`ts(7016)

**Expected behavior**
The typescript compiler expects to find .d.ts files

**Additional context**
The project may require a separate module that can be installed on typescript project for the typescript compiler run

**Comment by DanielAlongE** [comment]
Apparently there is a work around.

1. You can add a shim file to the root folder eg. shims-chakra.d.ts

2. then paste the following into the file:

`declare module "@chakra-ui/vue" {
  import Vue, { PluginObject }  from "vue";

  export default class Chakra {
    static install(v: typeof Vue, o?: PluginObject<unknown>): void
  }

  export class CThemeProvider extends Vue {}
  export class CReset extends Vue {}
}`

I recommend that this be adopted into the official docs for those using Typescript

**Comment by codebender828** [comment]
Hello @DanielAlongE ! Thank you for opening this issue. Also thank you for sharing the workaround for this.

I still think this is a solution we can include in the actual module, so I will re-open this issue for the sake of a more sustainable solution.

I don't have a very strong Typescript background, so if you're open to contributing toward this or even giving some suggestions for how to do it, that would be great!

**Comment by DanielAlongE** [comment]
@codebender828 I will start working on it right away

**Comment by creepinson** [comment]
any updates?
