### ISSUE TITLE
Consider adding `cross-env` as devDependencies for better development experience 

### ISSUE THREAD

**Issue by Namchee** [chakra-ui/chakra-ui-vue#277]
**Is your feature request related to a problem? Please describe.**
`storybook` script requires you to set environment variables called `STORYBOOK_VUE_DEV_TOOLS`. Unfortunately, `npm` scripts cannot set environment variables on Windows. 

To solve this issue, I suggest adding [cross-env](https://github.com/kentcdodds/cross-env) before setting the environment variables. `cross-env` works on Windows, Linux, and macOS.

**Comment by codebender828** [comment]
Good point. Thank you @Namchee. 

@koca Since you're our Window's ninja, do you think you could help review this when it's implemented?

**Comment by koca** [comment]
@codebender828 I use mac since 2015 (and will never look back) 😂  i do have a windows machine but for gaming maybe i can try there but idk let me see :D

**Comment by koca** [comment]
I don't think its a good idea to develop sth on windows. I suggest using something like WSL 2 for better dev experience.

**Comment by Namchee** [comment]
I haven't tried WSL2 yet since I have bad experiences from WSL. I'll give it a shot later.

Nonetheless, I'll create a pull request to address this issue as `cross-env` ensures maximum compatibility in most machines.

**Comment by wopian** [comment]
> and I don't think its a good idea to develop sth on windows. I suggest using something like WSL 2 for better dev experience.

That statement simply hasn't been true for the last 10 years. There are some low-level differences if you're interacting with the shell languages directly, like how Windows and *nix use a different syntax for environment variables but that and others are easily handleable.

There's nothing wrong with developing on Windows _without_ WSL(2) - it has excellent dev tooling and support like any other OS.
