### ISSUE TITLE
Docs: "Edit this page" leads to 404 on GitHub

### ISSUE THREAD

**Issue by vishnumohanrk** [chakra-ui/chakra-ui-vue#278]
The "Edit this page on GitHub" link at the end of docs page leads to 404 page not found on GitHub.

**Comment by codebender828** [comment]
Thanks for catching this. @vishnumohanrk 

I think it's because we changed the directory of the docs to `website`. I forgot to update the footer component accordingly.

**Comment by codebender828** [comment]
I can take fix it later this evening. Were you looking to contribute to the docs?

If you were then it might be of interest to you to know that the docs have been moved to the `website` directory in the repository root. 👍🏽

**Comment by vishnumohanrk** [comment]
In [this file](https://github.com/chakra-ui/chakra-ui-vue/blob/master/website/components/FileContributors.vue), made the following changes.

![image](https://user-images.githubusercontent.com/51525368/90328588-186e9480-dfbb-11ea-9057-0e7daf52fc54.png)

and it redirects to the files in [this folder](https://github.com/chakra-ui/chakra-ui-vue/tree/master/website/pages)

Is this right? Shall I open a PR?

**Comment by codebender828** [comment]
Yes this is it. Great! go ahead an open a PR for it if you're ready!

**Comment by codebender828** [comment]
Fixed in #279

**Comment by codebender828** [comment]
@all-contributors please add @vishnumohanrk for docs
