### ISSUE TITLE
CReset "config" prop defined as Object, but used as Function

### ISSUE THREAD

**Issue by freality** [chakra-ui/chakra-ui-vue#283]
The config prop on CReset is defined as an Object, but used as a function. 

This results in `[Vue warn]: Invalid prop: type check failed for prop "config". Expected Object, got Function` when a Function is passed in. Although, the component works properly. 

Passing in an Object results in `TypeError: this.config is not a function`.

Definition:
https://github.com/chakra-ui/chakra-ui-vue/blob/54022981387f99304e4d6226b31f87d18d521f05/packages/chakra-ui-core/src/CReset/CReset.js#L53-L55

Usage:
https://github.com/chakra-ui/chakra-ui-vue/blob/54022981387f99304e4d6226b31f87d18d521f05/packages/chakra-ui-core/src/CReset/CReset.js#L46-L51

**Comment by codebender828** [comment]
Hey, @freality ! Thanks for catching this! I must have forgotten to include the prop changes when I updated this component in the last refactor. Thanks for the catch. I'll also include some tests to make sure it doesn't break again. ❤️

**Comment by codebender828** [comment]
Also this issue is open for contribution!

**Comment by peoray** [comment]
I'd like to work on this and also add the tests to check for this to prevent breaking in the future. @codebender828 I'll need pointers on the test file :)

**Comment by codebender828** [comment]
Closed in #287
