### ISSUE TITLE
[Docs]: Add overscroll-x hidden to the main container

### ISSUE THREAD

**Issue by quannt** [chakra-ui/chakra-ui-vue#290]
**Is your feature request related to a problem? Please describe.**
Scrolling the document site on iPhone feels "unstable" due to overflown content on the x-asis. Here's a video https://www.dropbox.com/s/fq82se4052th76w/Video%209-4-20%2C%2022%2032%2010.mp4?dl=0

**Describe the solution you'd like**
Adding `overflow-x: hidden` on `CBox` in `layouts/default.vue` . Here's a video 
https://www.dropbox.com/s/laamga7hin0mmj0/Video%209-4-20%2C%2022%2033%2051.mp4?dl=0

Adding `overflow-x: hidden` could introduce a new problem with wide tables being cut off. However, this is easily fixable by wrapping the `<table>` inside a `div` and set `overflow-x: auto` on the `div`.

**Additional context**
vuejs.org and a lot of other sites is using the same approach of adding `overflow-x: hidden` to the main container.

**Comment by codebender828** [comment]
Hey @quannt ! Thanks for contributing this issue. Will look into this 👍
