### ISSUE TITLE
[chore]: Improve contributor setup documentation for testing

### ISSUE THREAD

**Issue by freality** [chakra-ui/chakra-ui-vue#301]
**Describe the bug**
When following the README.md instructions for contributing, testing fails.

**To Reproduce**
1. Clone repo `git clone git@github.com:chakra-ui/chakra-ui-vue.git && cd chakra-ui-vue`
2. [Follow Contrib instructions](https://github.com/chakra-ui/chakra-ui-vue#development-for-contributing)
```
yarn install
yarn bootstrap
yarn dev
```
3. Run test suite `yarn test`
4. The `yarn workspace @chakra-ui/nuxt test`  protion fails (see screenshot)

**Expected behavior**
All tests should pass. 

Running `yarn build` before testing resolves the issue. This seems to be caused by differences in the rollup dev config and rollup default config (dev config does not build cjs & umd artifacts)

Either:
- rollup dev config should match prod config
- `yarn test` should be include build; like `yarn test:core && yarn build && yarn test:module` 
- contrib docs should include something on running tests

_Note: I was struck by this problem when trying to push commits; so whatever change should allow pre-push hooks to works._

**Screenshots**
<img width="783" alt="Screen Shot 2020-09-12 at 9 45 40 PM" src="https://user-images.githubusercontent.com/15808/93008419-76eb4c00-f542-11ea-89e3-4e7bb0df1e09.png">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by codebender828** [comment]
Good point. This problem was caused by a lack in the documentation process for contribution. I think the best way to improve it going forward would be to include the `yarn build` step on project setup in the documentation.

Would this suffice?

**Comment by peoray** [comment]
This has been sorted out as the README has been updated to include `yarn build` in the contributing section.
