### ISSUE TITLE
v-scroll-lock is licensed as GPL-3

### ISSUE THREAD

**Issue by cilice** [chakra-ui/chakra-ui-vue#302]
**Is your feature request related to a problem? Please describe.**
We are unable to use chakra-ui in a commercial product due to `v-scroll-lock` GPL-3 license. This is a show stopper.

**Describe the solution you'd like**
Ideally, no licenses of the dependencies should be GPL-like. Apache-licensed works for us, MIT does too. 

**Describe alternatives you've considered**
Implementing an own wrapper component for `scroll-lock` library, and rewiring it.. but this is a lot of effort.
I also opened https://github.com/phegman/v-scroll-lock/issues/14 as an alternative.

**Additional context**
https://github.com/phegman/v-scroll-lock/blob/master/package.json#L10

**Comment by cilice** [comment]
Update:

@phegman changed the license of `v-scroll-lock` to `Apache-2` in the newest version `1.3.1 🎉

**Comment by codebender828** [comment]
Good news! Thank you @phegman! ❤️

Excited to see your project fly, @cilice 🚀
