### ISSUE TITLE
[bug]: Include missing style props

### ISSUE THREAD

**Issue by koca** [chakra-ui/chakra-ui-vue#303]
https://github.com/chakra-ui/chakra-ui-vue/blob/f06b2c5f2a8afcf201a4e0f8fae0939c0257be6b/packages/chakra-ui-core/src/config/props/props.js

Not working:

- flexGrow 
- borderTopLeftRadius (roundedTopLeft works)
- borderTopRightRadius
- borderBottomRightRadius
- borderBottomLeftRadius

WIP: i'll update the list if i find more.

**Comment by codebender828** [comment]
Thanks, @koca. Good catch. These can also be included incrementally as we find them.
