### ISSUE TITLE
Add more new properties css

### ISSUE THREAD

**Issue by harrytran998** [chakra-ui/chakra-ui-vue#310]
**Is your feature request related to a problem? Please describe.**
Instead of using `<c-flex justify="center" align="center">` --> `<c-flex place-content="center`>

**Describe alternatives you've considered**
Yeah, I want to apply the new css properties, like
`place-content`, `place-items`, and `place-self`

**Comment by codebender828** [comment]
Hey, @harrytran998 ! Thanks for catching this! I'll be sure to add them.

Up until this point, I've been updating our properties manually as encountered. As a more concrete solution, it would be better to keep track of them using a more complete set of all Chakra CSS properties
