### ISSUE TITLE
Create Nuxt App + ChakraUI + Nuxt + Static fails on initial project scaffold (CAvatar and CAvatarGroup components)

### ISSUE THREAD

**Issue by JessicaSachs** [chakra-ui/chakra-ui-vue#311]
**Describe the bug**
Throwing errors when scaffolding a basic project in Nuxt with Chakra in Static mode

```bash
 ERROR  [Vue warn]: Error in callback for watcher "nuxt.err": "ReferenceError: NuxtError is not defined"

(found in <Root>)


 ERROR  [Vue warn]: Error in nextTick: "ReferenceError: NuxtError is not defined"


 ERROR  NuxtError is not defined                                          08:27:43

  at Vue.errorChanged (server.js:290:27)
  at Watcher.run (node_modules/vue/dist/vue.runtime.common.dev.js:4554:19)
  at flushSchedulerQueue (node_modules/vue/dist/vue.runtime.common.dev.js:4298:13)
  at Array.<anonymous> (node_modules/vue/dist/vue.runtime.common.dev.js:1976:12)
  at flushCallbacks (node_modules/vue/dist/vue.runtime.common.dev.js:1902:14)
```

**To Reproduce**

Create a project (or clone [my example](https://github.com/JessicaSachs/chakra-nuxt-static-example))
```
create-nuxt-app v3.3.0
✨  Generating Nuxt.js project in chakra-nuxt-static-example
? Project name: chakra-nuxt-static-example
? Programming language: JavaScript
? Package manager: Yarn
? UI framework: Chakra UI
? Nuxt.js modules: (Press <space> to select, <a> to toggle all, <i> to invert select
ion)
? Linting tools: (Press <space> to select, <a> to toggle all, <i> to invert selectio
n)
? Testing framework: None
? Rendering mode: Universal (SSR / SSG)
? Deployment target: Static (Static/JAMStack hosting)
? Development tools: (Press <space> to select, <a> to toggle all, <i> to invert sele
ction)
? Version control system: Git
```

Then...

1. Go into the newly created project
2. Run yarn dev
3. Navigate to your app
4. See that the console throws an error :-(

**Expected behavior**
That it works fine and doesn't throw any errors

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser: Chrome
 - Version: `"@chakra-ui/nuxt": "^0.0.10",`

**Comment by JessicaSachs** [comment]
(Initially reported here https://github.com/nuxt/nuxt.js/issues/8093)

**Comment by pi0** [comment]
Hi. Reference error should be resolved with [nuxt@^2.14.6](https://github.com/nuxt/nuxt.js/releases/tag/v2.14.6). Maybe with upgrading you can investigate easier to see whats issue with `CAvatar` component.

**Comment by codebender828** [comment]
Thanks @pi0 ! Will upgrade and check it out.

**Comment by codebender828** [comment]
Hey @JessicaSachs! 

Thanks to @pi0's advice, upgrading to [nuxt@^2.14.6](https://github.com/nuxt/nuxt.js/releases/tag/v2.14.6) seemed to fix it. Try running upgrading on your project as well.
