### ISSUE TITLE
theme.fonts.body is not being applied to CReset

### ISSUE THREAD

**Issue by galaxyblur** [chakra-ui/chakra-ui-vue#312]
**Describe the bug**
`theme.fonts.body` is not being applied. (I am using the latest version of chakra-ui/nuxt, 0.0.13.)

**To Reproduce**
1. Extend theme in nuxt.config.js with extendTheme
2. Add `fonts.body`
3. Build site
4. Inspect any plain body element and see that it uses `html { font-family: sans-serif }` and not the theme's value.

**Expected behavior**
I would expect that html font-family be set to what I provide in my theme.

**Additional context**
Setting `fonts.heading` *does* work as expected. Additionally, I noticed that useTailwindPreflight() defines html font-family twice, where I'd expect one would suffice. I don't know how to prove that is the cause, though.

Thanks for your help.

**Comment by codebender828** [comment]
Hey @galaxyblur ! Thanks for opening this issue.

Do you want to create a [codesandbox](https://codesandbox.io/s/vue) to reproduce this so I can see it in code? Had trouble understanding how you were using the `fonts.body`.

**Comment by galaxyblur** [comment]
Sure. Per this page https://vue.chakra-ui.com/extending-theme I would expect the following to work: https://codesandbox.io/s/funny-visvesvaraya-wqr7t

**Comment by codebender828** [comment]
Thanks for the reproduction link. I now see what you mean. For this the CReset component would need to read the values from the theme object. Sounds like something that can be done in a new feature.

**Comment by codebender828** [comment]
If you're open to opening a new pull request for this that would be great. I soon intend to focus my efforts on the Vue 3 support version of Chakra UI Vue.

**Comment by codebender828** [comment]
No worries! Opened a pull request to fix this here: #323

**Comment by galaxyblur** [comment]
Thanks, but what does theme.fonts.body do if not this? I mean, is this really a new feature request or a bug?
