### ISSUE TITLE
[Bug] CInputLeftElement always on the top even open CDrawer

### ISSUE THREAD

**Issue by ryanC1993** [chakra-ui/chakra-ui-vue#313]
### Describe the bug
I found if the input component uses `CInputLeftElement` component, and opens the `CDrawer`, the CInputLeftElement still shows and not covered by CDrawer modal.

### To Reproduce
1. Go to https://vue.chakra-ui.com/input
2. Open Inspector, use the mobile view.
3. Click nav menu burger at the right top
<img width="722" alt="截圖 2020-09-19 上午11 06 51" src="https://user-images.githubusercontent.com/9876706/93657856-a3362980-fa68-11ea-995d-f915f8ba6dd7.png">

**Expected behavior**
CDrawer should cover everything, every components.

**Screenshots**
![image](https://user-images.githubusercontent.com/9876706/93657922-5bfc6880-fa69-11ea-975a-4c5b918fa7a8.png)
![image](https://user-images.githubusercontent.com/9876706/93657926-64ed3a00-fa69-11ea-9d91-02c5ed82b3b8.png)

**Comment by codebender828** [comment]
Hey @ryanC1993 ! Thanks for opening this issue. Will look into this!
