### ISSUE TITLE
Use toast in Vue 3 Composition API --> this[sourcekey] is undefined

### ISSUE THREAD

**Issue by harrytran998** [chakra-ui/chakra-ui-vue#320]
**Describe the bug**
Istead of using `this.$toast` in Vue 2, I use `setup()` function like this

```ts
setup(_, { root }) {
  function login() {
    // do logic
    if (sucess) {
      (root as any).$toast({ ... options here })
    }
  }
}
```
But in after do this, it show the Vue error warning in consle log
![image](https://user-images.githubusercontent.com/24296018/93989982-c3d9e880-fdb4-11ea-9c75-8655439b2f1b.png)

Then I clicks on CAlert:43, see here
![image](https://user-images.githubusercontent.com/24296018/93990081-e1a74d80-fdb4-11ea-93c5-95edebdf038f.png)

**Expected behavior**
If u can fix it, I love that 😊

**Desktop:**
 - Browser [firefox]
 - Version [81.0 (64-bit)]

**Comment by codebender828** [comment]
Hi @harrytran998 ! Thanks for the issue contribution.

Interesting. I haven't really encountered this problem yet. Could you share a link to a codesandbox with this issue so I can understand it better?

**Comment by codebender828** [comment]
Closed for dormancy. Please reopen if this issue is persistent 👍
