### ISSUE TITLE
[Documentation] Search box overlaps with code box when expanded

### ISSUE THREAD

**Issue by Namchee** [chakra-ui/chakra-ui-vue#336]
**Describe the bug**
The algolia search box suggestion overlaps with any code box present on any documentation page that contains code box.

**To Reproduce**
1. Go to [the website](https://vue.chakra-ui.com)
2. Navigate to any page that contains a code box, for example [here](https://vue.chakra-ui.com/getting-started).
3. Trigger the search suggestion by typing anything in the search box, for example `font`.
4. (If you have a really big viewport), scroll until the search suggestion intersect a code box.
5. See the error.

**Expected behavior**
The search suggestion shouldn't be stacked below the code box. It should **ALWAYS** be in the front for it to be readable on any condition.

**Screenshots**
This screenshot below is taken with Chrome

![form-bug](https://user-images.githubusercontent.com/32661241/94986311-eecbf580-0587-11eb-9384-f4ecc0445930.png)

**Desktop (please complete the following information):**
 - OS: Microsoft Windows 10 build 2004
 - Browser: Chrome, Firefox
 - Version: [Chrome] 85.0.4183.121, [Firefox] 82

**Additional context**
This issue is caused by [difference in the stacking context](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Positioning/Understanding_z_index/The_stacking_context). When we put a `position: relative` on any element, the browser will automatically create a new stacking context for that particular element. Since all code box has `position: relative` on it, it has a new stacking context which will be placed on top of anything with the default stacking context.

It seems that algolia tries to handle the issue by putting `z-index: 100` for the suggestion box. However, since the parent (the `form` element in this case) is placed on the default stacking context, it will always be placed below the code box.

The solution is quite simple, we just need to create a new stacking context for the `form` element. To make sure that it always placed on top of the box, I'll give a `z-index: 1` on it. I've created the pull request for it.

**Comment by codebender828** [comment]
Hey @Namchee Thanks for capturing this. I also appreciate having opened a pull request along with it!
