### ISSUE TITLE
Add the new utilities like Inset in TailwindCss

### ISSUE THREAD

**Issue by harrytran998** [chakra-ui/chakra-ui-vue#338]
**Is your feature request related to a problem? Please describe.**
Actually, instead of using 
```
top="0"
right="0"
bottom="0"
left="0"
```
We can replace them with [`inset-0` like Tailwind](https://tailwindcss.com/docs/top-right-bottom-left)~ 

**Describe the solution you'd like**
I think Chakra should have utilities folder in `lib/theme` folder on `chakra-ui-core` --> People can customize this like others

**Describe alternatives you've considered**
You can do one thing, and maybe I and the other can contribute this feature!

**Comment by codebender828** [comment]
Great idea! Thanks.

**Comment by codebender828** [comment]
This can be done here: 😄 

https://codesandbox.io/s/chakra-ui-vue-using-inset-exb27?file=/src/App.vue
