### ISSUE TITLE
C-tag varience-color auto generate with color .500

### ISSUE THREAD

**Issue by harrytran998** [chakra-ui/chakra-ui-vue#348]
**Describe the bug**
Like the title 🙈

**Expected behavior**
User can customize whatever color they want in that

**Screenshots**
In here, I want to use gray.200 --> Chakra generate with that color :( 
![image](https://user-images.githubusercontent.com/24296018/97772337-9ed95200-1b78-11eb-9645-2e388ebebb49.png)

**Comment by dombavetta** [comment]
@harrytran998 Can you please provide a project to help reproduce the issue, [CodeSandbox](https://codesandbox.io/) or [CodePen](https://codepen.io/) for example. Even a screenshot or code snippet from your project would help us to diagnose or troubleshoot this for you!
