### ISSUE TITLE
<c-input-group> block event on input

### ISSUE THREAD

**Issue by Maskim** [chakra-ui/chakra-ui-vue#349]
**Describe the bug**
I have this structure : 
```
<c-input-group>
	<c-input id="username" v-model="username" type="text" @input="checkUsernameAvailability()" />
	<c-input-right-element v-if="loading.username">
		<icon-loading />
	</c-input-right-element>
	<c-input-right-element v-else-if="!usernameIsInvalid && username !== ''" color="green.400">
		<icon-check />
	</c-input-right-element>
</c-input-group>
```

When I change the value of the input the @input event is not fired.

**Expected behavior**
@events needs to work when using this structure :)

**Desktop (please complete the following information):**
 - OS: Mac Hight Siera
 - Browser Firefox dev edition
 - Version 81.0b9

**Comment by bmulholland** [comment]
This isn't very answerable on its own. I'd suggest first getting it down to a shorter repro, eliminating extras:

* Does this still happen when you take out the `c-input-right-element`? If you take the input out of the group?
* Does it still happen if you change `checkUsernameAvailability` to something more basic?
* How do you know `checkUsernameAvailability` is set up properly?

**Comment by dombavetta** [comment]
Hey @Maskim, this is already being tracker in issue #292, there are several work arounds indicated in the thread. Please move any discussion over to there.
