### ISSUE TITLE
Import path to emotion module broken

### ISSUE THREAD

**Issue by JackieBinya** [chakra-ui/chakra-ui-vue#352]
**Describe the bug**
I am working on a brand new vuejs(Vue 2) project in my local.
I followed basic project set up instructions used Vue CLI to scaffold the app, used npm to install chakra-ui-vue, configured chakra in _~/main.js_ and then I launched my dev environment. 

The app is broken the homepage is not rendered - its blank and on the console I got the message shown in the screenshot below:

**Screenshots**
![update-emotion](https://user-images.githubusercontent.com/50267279/100423923-82580900-3095-11eb-94a3-999e9882341d.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Ubuntu focal fossa
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] latest

**Smartphone (please complete the following information):**

**Additional context**

**Comment by codebender828** [comment]
Hello @JackieBinya. Thanks for catching this. Will take a look at it as
soon as I can and get back to you on this thread.
