### ISSUE TITLE
Menu does not work with v-if

### ISSUE THREAD

**Issue by outofgamut** [chakra-ui/chakra-ui-vue#353]
When I put the menu component inside <template v-if="someCondition"></template> and someCondition's value toggles, the menu component doesn't show/hide as expected.

**To Reproduce**
https://codesandbox.io/s/chakra-ui-vue-starter-forked-kmy99?file=/src/main.js

**Expected behavior**
Menu button should show/hide when "toggle menu" button is clicked.

**Screenshots**
None

**Desktop (please complete the following information):**
 - MacOS Big Sur
 - Chrome

**Comment by codebender828** [comment]
Hey @outofgamut 

thanks for capturing this issue.

**Comment by peoray** [comment]
@outofgamut Not sure why it doesn't work with the `template` but if you use `CBox`, it works fine and it doesn't add any extra HTML tag. Here is a demo: https://codesandbox.io/s/chakra-ui-vue-starter-forked-kmy99?file=/src/App.vue
