### ISSUE TITLE
Why Vue throws an error, when dealing with color modes?

### ISSUE THREAD

**Issue by BroJenuel** [chakra-ui/chakra-ui-vue#359]
- I have created a new Project
- I installed the framework using  `vue add chakra-ui`
- Setup the main js following the instruction in https://vue.chakra-ui.com/color-mode
![image](https://user-images.githubusercontent.com/31676163/102073947-04d71b80-3e3f-11eb-90be-ae20056ae4c7.png)

But when I try to run the using `yarn serve`

I see this error.
![image](https://user-images.githubusercontent.com/31676163/102073987-0e608380-3e3f-11eb-9895-6392a7e96136.png)

**Comment by codebender828** [comment]
Hey @BroJenuel ! Thanks for opening this. Which version of `@chakra-ui/vue` do you have installed?

**Comment by BroJenuel** [comment]
> Hey @BroJenuel ! Thanks for opening this. Which version of `@chakra-ui/vue` do you have installed?

I installed the latest  chakra version

**Comment by codebender828** [comment]
The fix for this requires that the `CColorModeProvider` has only one child element. I'll be cliosing this for now due to inactivity. Feel free to reopen if it persists
