### ISSUE TITLE
I like To Contribute but this Happens.

### ISSUE THREAD

**Issue by BroJenuel** [chakra-ui/chakra-ui-vue#362]
running this command gave me this error `yarn bootstrap`

![image](https://user-images.githubusercontent.com/31676163/102497726-f5143d00-40b3-11eb-9cf5-57620fdd7991.png)

**Comment by codebender828** [comment]
Hey @BroJenuel ! Thanks for reporrting this. Tomorrow I'll be fixing this. Was able to discover the cause of the issue.
