### ISSUE TITLE
CAvatarGroup size prop not working

### ISSUE THREAD

**Issue by BroJenuel** [chakra-ui/chakra-ui-vue#363]
I am using the CAvatarGroup component but adding the size prop doesn't work. Adding the size prop will create a space below the group avatars.

![image](https://user-images.githubusercontent.com/31676163/102497986-5805d400-40b4-11eb-8197-9f708694b1ed.png)

**Comment by peoray** [comment]
@BroJenuel The `CAvatarGroup ` uses the `group-size` prop. This isn't indicated in the documentation. Thanks for spotting it out, the team will update accordingly :) 

```
// `group-size prop takes the same values as the `size` prop
<c-avatar-group max="3" group-size="sm"> 
  <c-avatar name="Evan You" src="https://bit.ly/chakra-evan-you" />
  <c-avatar name="Jonathan Bakebwa" src="https://bit.ly/chakra-jonathan-bakebwa" />
  //  ...
</c-avatar-group>
```

**Comment by BroJenuel** [comment]
Thanks 👍👍
