### ISSUE TITLE
When running the command yarn install, their is an error.

### ISSUE THREAD

**Issue by BroJenuel** [chakra-ui/chakra-ui-vue#369]
**Describe the bug**
I like to contribute since I am using this library in a project that we are making, but when I tried to fork, and cloned and then run the command `yarn install`.

This error shows up:
![image](https://user-images.githubusercontent.com/31676163/103332032-7cde4c00-4aa3-11eb-8a03-47efe115f691.png)

Machine:
node version: v14.15.1
Windows 10

**Comment by codebender828** [comment]
Hey @BroJenuel . Hmmm. This looks quite strange to me. I haven't experienced this before.

From the look of things it looks like the version of the Node.js you are running is ^14. Have you tried installing the libraries again using node version of ^12.19? It seems to be a stable version of node.js. My suspicion is that one of Chakra's dependency libraries doesn't have bindings for Node v.14.

You could also look into installing Python, seeing as there is `cannot find Python executable "python" error`.

**Comment by BroJenuel** [comment]
> Hey @BroJenuel . Hmmm. This looks quite strange to me. I haven't experienced this before.
> 
> From the look of things it looks like the version of the Node.js you are running is ^14. Have you tried installing the libraries again using node version of ^12.19? It seems to be a stable version of node.js. My suspicion is that one of Chakra's dependency libraries doesn't have bindings for Node v.14.
> 
> You could also look into installing Python, seeing as there is `cannot find Python executable "python" error`.

Oh, right let me try using node 12, and i have python installed.

**Comment by koca** [comment]
Unfortunatelly i don't use windows for frontend stuff(i use mac). I recommend you to use wsl2 for better dev experience. I've used it. It was great.

**Comment by codebender828** [comment]
Hey @BroJenuel ! Are you still experiencing this issue?

**Comment by BroJenuel** [comment]
> Thanks @koca for the suggestion ❤️.
> 
> Hey @BroJenuel ! Are you still experiencing this issue?

Good day, yeah Im still having travel installing dependencies
![image](https://user-images.githubusercontent.com/31676163/104440412-463d2100-55cd-11eb-9daa-38872332ad75.png)

its checking python, but I have a python in my system.
![image](https://user-images.githubusercontent.com/31676163/104440536-72f13880-55cd-11eb-86a4-500f53e0f667.png)

how to set it up in windows.

**Comment by BroJenuel** [comment]
> Unfortunatelly i don't use windows for frontend stuff(i use mac). I recommend you to use wsl2 for better dev experience. I've used it. It was great.

Oh I just red this, hmm let me try using wsl2 then :)

**Comment by BroJenuel** [comment]
I tried again but still, I'm getting this kind of error

![image](https://user-images.githubusercontent.com/31676163/104919329-0ad99280-59d1-11eb-81dd-79268d4c3bd7.png)
