### ISSUE TITLE
'bg' property doesn't work with dot notation

### ISSUE THREAD

**Issue by azerpas** [chakra-ui/chakra-ui-vue#377]
**Describe the bug**

I'm trying to color the background of my CBox element with 'bg' and dot notation 'indigo.400' with no success. 

**To Reproduce**
- Add a CBox element
- Add a 'bg' prop with dot notation

**Expected behavior**

Expected: Indigo background with CSS generated.      
Actually: Nothing appears in CSS.     

**Additional context**
0.7.2v

**Comment by koca** [comment]
![image](https://user-images.githubusercontent.com/342666/104107607-92871900-52ce-11eb-8486-4c995463c321.png)

Hi @azerpas, Thanks for the report but i guess you didn't setup ChakraUI properly. What framework are you using? Also can you upgrade to latest version which is `0.7.4`?

**Comment by azerpas** [comment]
Sorry, meant 0.7.4. 

Using vue-cli. Emotion is also installed.

Here's my set-up:
```
import Vue from 'vue'
import App from './App.vue'
import Chakra, { CBox } from '@chakra-ui/vue'
import router from './router';
import { CThemeProvider, CColorModeProvider, CReset } from '@chakra-ui/vue';
import theme from "./theme";

require('dotenv').config()

Vue.config.productionTip = false

Vue.use(Chakra, { extendTheme: theme });

new Vue({
    router,
    render: (h) => h(CThemeProvider, [
        h(CColorModeProvider, [
            h(CBox, [
                h(CReset),
                h(App)
            ])
        ])
    ])
}).$mount('#app')
```

**Comment by koca** [comment]
I don't see any issues except unneceseary imports.
Did you install `emotion` or `@emotion/css`? You need to install `@emotion/css`.
Here is a working example of `main.js`:

```js
import Vue from "vue";
import App from "./App.vue";
import Chakra, {
  CThemeProvider,
  CColorModeProvider,
  CBox,
  CReset
} from "@chakra-ui/vue";

// example theme
const theme = {
  colors: {
    customRed: "red"
  }
};

// Import Chakra UI Plugin and register it.
Vue.use(Chakra, { extendTheme: theme });

Vue.config.productionTip = false;

new Vue({
  render(h) {
    // Mount our application inside the
    // ThemeProvider and ColorModeProvider components :)
    return h(CThemeProvider, [
      h(CColorModeProvider, [h(CBox, [h(CReset), h(App)])])
    ]);
  }
}).$mount("#app");

```

**Comment by codebender828** [comment]
Hey @azerpas !

Thanks for opening this issue. Feel free to re-open this again if you still have this issue. You can also share a reproduction to the issue using this codesandbox template:

https://codesandbox.io/s/charming-frog-z3bp4

Will close this for now until necessary to re-open.
