### ISSUE TITLE
Overwrite components's baseStyles in extend theme config file

### ISSUE THREAD

**Issue by anqaka** [chakra-ui/chakra-ui-vue#379]
Is it possible to overwrite component's baseStyle using extend theme config file?

Example:I would like to use button width `rounded: 0` but not adding this each time I use the button in a components. 
Instead of using:
(in Component.vue)
```
<CButton
  rounded="0"
>
  Button
</Cbutton>
```

It would be great to use something like:
(in custom-theme.js):
```
export default {
    colors: {
        ...
    },
    components: {
        button: {
           rounded: '0'
        }
    }
}
```
Something like in Chakra-ui for React: https://chakra-ui.com/docs/theming/customize-theme#customizing-single-components

**Comment by codebender828** [comment]
Hey @anqaka ! Thanks for opening this issue.

We'll be introducing this in the next major version of Chakra UI Vue. We already have it in development here:

https://github.com/chakra-ui/chakra-ui-vue-next
