### ISSUE TITLE
Could not find a declaration file for module '@chakra-ui/vue'

### ISSUE THREAD

**Issue by ahmetyasirkilic** [chakra-ui/chakra-ui-vue#381]
### **I could not establish the chakra-ui anyway. All I do is create a vue project and import chakra-ui. Is there a place I missed? I am thinking of switching to React otherwise: D**

**Screenshots**
![Screenshot_5](https://user-images.githubusercontent.com/17856904/106049948-c1d3bd80-60f7-11eb-9633-5e38a61158c0.png)
![Screenshot_](https://user-images.githubusercontent.com/17856904/106050900-c9e02d00-60f8-11eb-9b9a-73d6d22c07c3.png)

**package.json**
``` javascript
"dependencies": { 
"@chakra-ui/vue": "^0.7.4",
    "@emotion/css": "^11.1.3",
    "core-js": "^3.6.5",
    "vue": "^3.0.0",
    "vue-router": "^4.0.0-0"
  },
  "devDependencies": {
    "@vue/cli-plugin-babel": "~4.5.0",
    "@vue/cli-plugin-router": "~4.5.0",
    "@vue/cli-service": "~4.5.0",
    "@vue/compiler-sfc": "^3.0.0"
  },
```

**Comment by codebender828** [comment]
Hey @ahmetyasirkilic !

I see that you're using @chakra-ui/vue@0.x for vue@3.x. At the moment it's only compatible with vue@2.x.

The Vue 3.x compatible version of @chakra-ui/vue is still in development at #chakra-ui/chakra-ui-vue-next.

**Comment by ahmetyasirkilic** [comment]
> 
> 
> Thanks @codebender828  
> 
> I don't know how i missed such a thing 😄
