### ISSUE TITLE
Set accordion "CCollapse" height to auto on animation end

### ISSUE THREAD

**Issue by IHIutch** [chakra-ui/chakra-ui-vue#383]
**Describe the bug**
CCollapse component retains the final height after the open animation finishes. This causes the wrapping div to stay the same size, even when the contents inside change (grow/shrink). Setting it to "auto" once the animation is complete would allow the wrapper to scale with the content.

**To Reproduce**
1. Add an Accordion component with some content inside the CAccordionPanel slot
2. Change the contents so that it has a smaller or bigger height than before
3. The CCollapse stays the same size

**Expected behavior**
CCollapse gets set to `height: auto` so that it scales with the inner content

**Screenshots**
My case was a nested accordion:
![Kapture 2021-02-03 at 11 31 52](https://user-images.githubusercontent.com/20825047/106779153-b65f2580-6614-11eb-95f8-732416aabf3e.gif)

Adding `height: auto`: 
![Kapture 2021-02-03 at 11 32 44](https://user-images.githubusercontent.com/20825047/106779168-b9f2ac80-6614-11eb-95d7-e8748888980b.gif)

Thanks!

**Comment by IHIutch** [comment]
I can rename this if it makes more sense to be something else `data-chakra-component="CCollapse"` is the element that actually gets the height, but its not technically a "Chakra component"

**Comment by codebender828** [comment]
Hey @IHIutch ! Thanks for opening an issue for this! Awesome work coming up with a solution for this! 

At the moment I've been focused on Vue 3 version support. If you can open a PR for it I can review it and have it merged for the `v0.7.5` release this weekend.

**Comment by IHIutch** [comment]
I'd be happy to contribute, although I'm not super familiar with how Chakra generates CSS under the hood. I'll take a look and see if I can understand it enough to chip in.

**Comment by codebender828** [comment]
Thank you @IHIutch !
