### ISSUE TITLE
CBox used inside CAspectRatioBox has no children nodes/content when rendered in the DOM

### ISSUE THREAD

**Issue by philwolstenholme** [chakra-ui/chakra-ui-vue#392]
**Describe the bug**
I am trying to use a CBox inside a CAspectRatioBox but I can't get any children components/content to appear.

Am I doing something wrong or is this a bug? I'm not sure :) 

**To Reproduce**
1. Go to https://codesandbox.io/s/chakra-ui-nuxt-demo-forked-hxshn?file=/pages/index.vue
2. Verify that the 'See the Vue' heading inside the CBox is not visible

**Expected behavior**
Any child components or DOM nodes should be visible 

**Screenshots**
![Screenshot 2021-02-26 at 13 41 05](https://user-images.githubusercontent.com/6339853/109307291-4ff6ad00-7838-11eb-87c3-b26ab3a3a5d3.png)

** Version numbers**

https://codesandbox.io/s/chakra-ui-nuxt-demo-forked-hxshn?file=/package.json:330-491

```
    "@chakra-ui/vue": "0.5.0",
    "@nuxt/http": "^0.3.0",
    "@nuxtjs/emotion": "0.0.1",
    "emotion": "10.0.27",
    "nuxt": "^2.5.1",
    "reqlim": "^0.0.0"
```

https://codesandbox.io/s/chakra-ui-nuxt-demo-forked-hxshn?file=/yarn.lock

**Comment by philwolstenholme** [comment]
I suppose with `iframe` or `img` or `picture` elements the child node content isn't important, but I was trying to use it to contain some HTML markup with children rather than just a single element.

**Comment by IHIutch** [comment]
Im also having issues with CAspectRatioBox using nuxt. I'm trying to do this: 
```
<CAspectRatioBox :ratio="21 / 9">
    <client-only>
        ....
    </client-only>
</CAspectRatioBox>
```

But am getting this error: `Cannot read property '0' of undefined`. It seems like CAspectRatioBox expects some element to live inside it.
