### ISSUE TITLE
CStack doesn't allow its children to be empty

### ISSUE THREAD

**Issue by MaySoMusician** [chakra-ui/chakra-ui-vue#425]
**Describe the bug**
When CStack has no children (i.e. default slot is empty), the runtime error of "filter of 'undefined'" will occur.

**To Reproduce**
(I'm experiencing this in Nuxt.)
1. Go to https://codesandbox.io/s/epic-nash-q7bgo?file=/src/App.vue
2. See Console
3. You will get `TypeError: Cannot read property 'filter' of undefined`

**Expected behavior**
No errors occurs

**Additional context**
https://github.com/chakra-ui/chakra-ui-vue/blob/782fecd8b57a4e064fe0342c89ed2d998960f9ec/packages/chakra-ui-core/src/CStack/CStack.js#L78-L80

We have to first check if `default` exists under `this.$slots`

**Comment by faaizajaz** [comment]
Running into this problem as well. Doesn't seem to affect functionality for now, but not nice seeing all that red in the console.

**Comment by codebender828** [comment]
Hey! @faaizajaz @MaySoMusician 

I've Included a fix for this in the codesandbox generates in #455 Thanks for helping us catch the issue. Try testing it and give us your feedback.

**Comment by faaizajaz** [comment]
Fantastic @codebender828! Not entirely sure how to test as the PR isn't merged--should I go in and make the change manually? Don't want to break anything...

Thanks by the way for your work on this. It's really a pleasure to use, and your documentation is excellent.

**Comment by codebender828** [comment]
Thank you @faaizajaz. I appreciate the comment. It's really encouraging as there's a lot to be done :D

You can test the PR on [**this codesandbox**](https://codesandbox.io/s/elastic-tereshkova-7bp5g) before I merge it.

**Comment by faaizajaz** [comment]
@codebender828 looks like it work! Thanks for closing this.
