### ISSUE TITLE
Problem with the Chakra-Vue Drawer page

### ISSUE THREAD

**Issue by k16e-me** [chakra-ui/chakra-ui-vue#429]
Kindly watch the following Loom and notice how a whitespace is at the bottom of the Drawer page. And then when you select each orientation where you want the Drawer to open, the page jumps to white/blank...quite disorienting.

https://vue.chakra-ui.com/drawer

https://www.loom.com/share/846ca6a69f814a9099dc75152dcca715

**Comment by peoray** [comment]
@k16e-me The loom video doesn't play. Can you provide more information on this?

**Comment by k16e-me** [comment]
I might've deleted that video since. When I have the time, I might take a look at Chakra again, and if it hasn't been fixed, re-issue. Thanks.
