### ISSUE TITLE
Can't use custom color from theme in Button component

### ISSUE THREAD

**Issue by ejirocodes** [chakra-ui/chakra-ui-vue#443]
trying to use custom color from theme object in button component

That's not working

`` <c-button variantColor="spasora.400" size="md" >Save</c-button>``

But when using the same color in the Box component, it's working fine:

``` <c-box bg="spasora.400" w="100%" p="4" color="white">This is the Box</c-box>```
here is the example:

My custom theme
export default {
  colors: {
    spasora: {
      50: "#dffafa",
      100: "#c3eae7",
      200: "#a2d9d7",
      300: "#81c8c5",
      400: "#3F8F8B",
      500: "#469f9b",
      600: "#347c78",
      700: "#225a56",
      800: "#0c3635",
      900: "#001512"
    }
  }
};

**Comment by codebender828** [comment]
Hey @ejirocodes ! You can use your custom variant color bu just passing the `variant="spasora"` prop. No need add the `.400`

**Comment by codebender828** [comment]
Will close this for now

**Comment by ejirocodes** [comment]
Thanks @codebender828, `variant="spasora"` didn't work so I `variant-color="spasora"` and it worked like magic!
