### ISSUE TITLE
CSS properties all appearing inside of font-family style rule.

### ISSUE THREAD

**Issue by DRD161** [chakra-ui/chakra-ui-vue#451]
**Describe the bug**
When using some style props such as gridRow and alignSelf, the css rules that are created are all jumbled up inside of a font-family style rule. In some instances these style props do not cause this issue.

**To Reproduce**
1. Go to https://github.com/DRD161/Gridsome-Portfolio.git
2. Download project
3. Open project directory and run `npm install` to install dependencies.
4. Run `gridsome develop` to start project.
5. View the 'About Me' section, the About Me header style props do not work properly. A bunch of the style rules are jumbled up inside of the font-family rule (see screenshot).

**Expected behavior**
The style props should output the correct css rules.

**Screenshots**
<img width="1680" alt="Screen Shot 2021-06-24 at 6 47 52 PM" src="https://user-images.githubusercontent.com/29187448/123342008-eef89080-d51c-11eb-9eca-981eac954a19.png">

**Desktop (please complete the following information):**
 - OS: MacOS Catalina version 10.15.7
 - Browser Firefox, Chrome
 - Version Firefox version 89.0.2, Chrome version 91.0.4472.114

**Comment by DRD161** [comment]
I now have this behavior when using the my style prop. 
`        <c-heading as="h3" size="lg" my="4">Web Development</c-heading>
`

I'm not sure if it's something I'm doing wrong but any help would be appreciated.

<img width="1680" alt="Screen Shot 2021-06-24 at 9 01 29 PM" src="https://user-images.githubusercontent.com/29187448/123353477-9c749f80-d52f-11eb-8705-0bbdef941efa.png">

**Comment by DRD161** [comment]
Just realized this bug was being caused by a typo in my custom theme file :sweat:. Mystery solved.

**Comment by codebender828** [comment]
:)
