### ISSUE TITLE
qn: Error using $chakraColorMode method with typescript

### ISSUE THREAD

**Issue by lianulloa** [chakra-ui/chakra-ui-vue#469]
**Describe the bug**
I have just create a brand new nuxt.js project, with chakra-ui and typescript and if I set script tag's lang attribute to "ts", then it marks me an error over any use of
this.$chakraColorMode(), this.$chakraTheme(), this.$toggleColorMode, this.$toast()

The error: Property '$chakraColorMode' does not exist on type 'CombinedVueInstance<Vue, unknown, unknown, unknown, Readonly<Record<never, any>>>'.Vetur(2339)

Is there any way to work around this??

**To Reproduce**
1. create a nuxt app with `yarn create nuxt-app <project-name>`
2. Select chakra-ui and typescript modules
3. [Activate runtime linting](https://typescript.nuxtjs.org/guide/lint#runtime-lint)  (ignore static/.sw.js)
4. See error in [page index](https://github.com/lianulloa/nuxt-typescript-chakra-ui-learning/blob/cd968de9c74b6d806f01eda94bd413cb9eb72ed9/pages/index.vue#L147)

**Expected behavior**
Have no errors since this method is injected by chakra-ui

**Screenshots**
<img width="1425" alt="Captura de Pantalla 2021-07-20 a la(s) 1 41 47 a m" src="https://user-images.githubusercontent.com/29025113/126267776-e8d00672-b89f-4c7b-afa9-98be216ac47b.png">

**Desktop (please complete the following information):**
 - OS: [e.g. MacOS Big Sur]

**Comment by codebender828** [comment]
Attempted to create a repo that types some of the properties here. Wanna take a look? @lianulloa 

https://github.com/codebender828/recreate-v0-typescript-injectables/blob/main/theme.d.ts

**Comment by lianulloa** [comment]
@codebender828 [theme.d.ts](https://github.com/codebender828/recreate-v0-typescript-injectables/blob/main/theme.d.ts) did the trick for the errors inside the file, but I still get these ones on the console

<img width="1368" alt="Captura de Pantalla 2021-07-21 a la(s) 12 24 36 a m" src="https://user-images.githubusercontent.com/29025113/126430620-7c8ca299-2292-40a1-a12b-6e48c3840e75.png">

the good part is that it doesn't prevent the app from starting

**Comment by lianulloa** [comment]
@codebender828 Also, by default `$chakraTheme` is used as a function (and it is defined as function inside theme.d.ts as well) but it is `undefined`.

Instead I can use it through `this.$chakra.theme` (found this by searching in [chakra-ui's doc for vue](https://vue.chakra-ui.com)) but it then shows an error

**Comment by Pwuts** [comment]
Since `$chakraTheme`, `$chakraColorMode` are provided by `CThemeProvider` and `CColorModeProvider`, and only exist within those components, I think it makes little sense to declare them on the global `Vue` instance. However, as it is intended for global use, it might make sense to move this functionality out of those two components into a client-side plugin which actually makes these properties available on the Vue instance and context.

**Comment by codebender828** [comment]
@Pwuts Good point. I've seen the pull request onn #473. It looks good. Does it satisfy the typescript requirements for component properties?

**Comment by Pwuts** [comment]
@codebender828 I'll look into the props specifically when I have time, which is going to be monday at the earliest.

**Comment by lianulloa** [comment]
I updated my package.json to use `"@chakra-ui/nuxt": "^0.4.0"` ( I think the fix got deployed there) but I still need `theme.d.ts` to remove the errors.

Also, the default example gets broken (in Nuxt)

<img width="1288" alt="Captura de Pantalla 2021-08-18 a la(s) 2 11 18 a m" src="https://user-images.githubusercontent.com/29025113/129846792-4594c721-f8bc-4858-acac-6250879ff75c.png">
