### ISSUE TITLE
Import and use toast component in a JavaScript file 

### ISSUE THREAD

**Issue by ejirocodes** [chakra-ui/chakra-ui-vue#470]
I've been trying to import the Toast component using `import { CToast } from '@chakra-ui/nuxt'; ` and `import CToast from "@chakra-ui/vue/src/CToast"` so I can use it to display error messages in my JavaScript file but I keep getting 👇🏽 

<img width="568" alt="Screen Shot 2021-07-20 at 17 56 52" src="https://user-images.githubusercontent.com/45228014/126364856-ab0d2e2e-de4a-4b30-aaac-f1d112124a4d.png">

**Comment by peoray** [comment]
@ejirocodes Thanks for opening an issue :) Can you create a reproduction using Codesandbox?

**Comment by peoray** [comment]
Please check the [docs](https://vue.chakra-ui.com/toast). Will be closing this for now. Let us know if you're still having this issue
