### ISSUE TITLE
TextArea: Error when using the event @change

### ISSUE THREAD

**Issue by abhinav-sharma-intuit** [chakra-ui/chakra-ui-vue#485]
**Describe the bug**
The issue with the text-area component:

```

<CTextarea
   v-model="textareaContent"
   maxWidth="sm"
   mx="auto"
   mt="2"
   placeholder="Here is a sample placeholder"
   size="md"
   :value="textareaContent"
   @change="onChange"
/>

methods: {
  onChange (e) {
    console.log(e)
  }
}
```

**Screenshots**
![image](https://user-images.githubusercontent.com/81356090/132937987-999ab6f2-6adb-45c2-8d39-7a8e2817b745.png)

**Comment by peoray** [comment]
Thank you @abhinav-sharma-intuit. This issue is already reported here #356. We are aware of it and will be fixed in the next release. I'll ensure to ping you here but for now, will be closing this since it's a duplicate :)
