### ISSUE TITLE
Storybook component issues

### ISSUE THREAD

**Issue by TNieminen** [chakra-ui/chakra-ui-vue#49]
## Description

At https://chakra-ui-vue.netlify.com some of the components are throwing errors on render or not working as expected. See list of screenshots for description

## Screenshots of broken components

![Screenshot from 2020-03-15 13-30-43](https://user-images.githubusercontent.com/24986078/76696019-bf27cf80-66c1-11ea-977c-4f224444a3f9.png)
![Screenshot from 2020-03-15 13-30-33](https://user-images.githubusercontent.com/24986078/76696021-c18a2980-66c1-11ea-985c-b7ef06e543ee.png)
![Screenshot from 2020-03-15 13-30-30](https://user-images.githubusercontent.com/24986078/76696022-c3ec8380-66c1-11ea-8462-2b06171c7939.png)
![Screenshot from 2020-03-15 13-30-27](https://user-images.githubusercontent.com/24986078/76696024-c5b64700-66c1-11ea-80c0-d8b426ad2c68.png)
![Screenshot from 2020-03-15 13-25-09](https://user-images.githubusercontent.com/24986078/76696026-c949ce00-66c1-11ea-8bea-a984dbe63438.png)

### Slider not reacting to drag

![slider-broken](https://user-images.githubusercontent.com/24986078/76696063-3cebdb00-66c2-11ea-987c-036cf992fc9d.gif)

### Progress component not showing anything

![Screenshot from 2020-03-15 13-30-17](https://user-images.githubusercontent.com/24986078/76696025-c7800a80-66c1-11ea-8296-989076f8833b.png)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Chrome
 - Version: 80.0.3987.116 (Official Build) (64-bit)

**Comment by DominusKelvin** [comment]
Thanks for catching this. We would be on it shortly.

**Comment by koca** [comment]
I'm working on this.

**Comment by jonybekov** [comment]
Hi. "Slider not reacting to drag" this issue has not been resolved in 0.7.4 version
