### ISSUE TITLE
Unrenderable Icons with FontAwesome Pro Duotone

### ISSUE THREAD

**Issue by dhazelett** [chakra-ui/chakra-ui-vue#495]
**Describe the bug**
When attempting to load `@fortawesome/pro-duotone-svg-icons` icons, only half the icon renders, and raises: `Error: <path> attribute d: Expected path command, "….06 0 0 0 64 64z,M396.8 288h-8.3…".` in the console

**To Reproduce**
Basic Vue2 install via `vue create project` & `vue add chakra-ui`

```js
import Chakra from '@chakra-ui/vue';
import { faUsers } from '@fortawesome/pro-duotone-svg-icons';

Vue.use(Chakra, {
  iconPack: 'fa',
  iconSet: { faUsers },
})

<c-icon name="users" />
```

**Expected behavior**
Both parts of the svg should render

**Screenshots**
This is how it's currently rendering
![image](https://user-images.githubusercontent.com/9557399/138575484-db1b8b47-f784-4e3a-8919-a600232ee641.png)

This is what it should look like
![image](https://user-images.githubusercontent.com/9557399/138575478-073a0528-e28e-4e19-a8d1-b331f124d272.png)

**Additional context**
The error appears in `utils/icons`, specifically here: https://github.com/chakra-ui/chakra-ui-vue/blob/develop/packages/chakra-ui-core/src/utils/icons.js#L15

I've just discovered this and will fork and make a PR likely tomorrow morning, if someone doesn't beat me to it.

**Comment by peoray** [comment]
I'll be closing this issue as the PR linked fixes it. If that's not the case, feel free to reopen it :)
