### ISSUE TITLE
CMenuOptionGroup throws a warning when passing an Array as a :value prop

### ISSUE THREAD

**Issue by Exilibris** [chakra-ui/chakra-ui-vue#497]
**Describe the bug**
Documentation says CMenuOptionGroup accepts string, number, Array<string or number> as a value of the :value attribute. However, when array is passed a warning is thrown in the console:

`Invalid prop: type check failed for prop "value". Expected String, Number, got Array`

However, components itself work as expected.

**To Reproduce**
1. Create a menu with the following contents in the dev environment:
```
<c-menu-option-group title="Country" type="checkbox" :value="['email','phone']">
      <c-menu-item-option value="email">Email</c-menu-item-option>
      <c-menu-item-option value="phone">Phone</c-menu-item-option>
      <c-menu-item-option value="country">Country</c-menu-item-option>
</c-menu-option-group>
```
2. See the error in the console.

**Expected behavior**
No errors shown, since Array value for this prop is documented.

**Desktop (please complete the following information):**
 - MacOS latest
 - Chrome latest

**Comment by peoray** [comment]
Thank you @Exilibris. This will be fixed in the next release :)
