### ISSUE TITLE
Responsive styles breaking issue since v0.10.x

### ISSUE THREAD

**Issue by carwack** [chakra-ui/chakra-ui-vue#504]
**Describe the bug**
There are some breaking bugs when using responsive styles in v0.10.x

*** Array Notation***
example: 
```
:width="[
  '80vw', // base
  '60vw', // 480px upwards
  '50vw', // 768px upwards
  '40vw', // 992px upwards
]"
```
This does not generate any media Queries at all.

*** Object Notation***
example: 
```
:width="{
  base: '80vw', // base
  sm: '60vw', // 480px upwards
  md: '50vw', // 768px upwards
  lg: '40vw', // 992px upwards
}"
```
The order of the media Queries inside the CSS isn't correct. 
![Screenshot 2021-12-24 at 13 46 12](https://user-images.githubusercontent.com/16015740/147353696-bff376d4-efd4-452d-8e33-d628714f63e0.png)

**To Reproduce**
1. Go to ['CodeSandBox example'](https://codesandbox.io/s/intelligent-edison-wu6bq?file=/src/App.vue:131-300&resolutionWidth=903&resolutionHeight=568)
2. Try to change the screen size

**Expected behavior**
When using responsive styles I would expect the media queries to be added to my CSS correctly.

**Additional context**
Works on v0.9.x but not on v0.10.x

**Comment by codebender828** [comment]
This issue only appears to be happening with the object syntax

**Comment by codebender828** [comment]
Thanks for the reproduction. Will look into this
