### ISSUE TITLE
Accessibility report link typo in CircularProgress component

### ISSUE THREAD

**Issue by givensuman** [chakra-ui/chakra-ui-vue#535]
The [CircularProgress component documentation](https://vue.chakra-ui.com/circularprogress) links to

`
https://github.com/chakra-ui/chakra-ui-vue/blob/master/packages/chakra-ui-core/src/CCircularProgress/accesibility.md
`

which contains a typo, and leads to a dead page. Should read

`
https://github.com/chakra-ui/chakra-ui-vue/blob/master/packages/chakra-ui-core/src/CCircularProgress/accessibility.md
`

**Comment by carwack** [comment]
Nice catch and thanks for letting us know! 🙏
Will be fixed asap!

**Comment by carwack** [comment]
Fixed in: https://github.com/chakra-ui/chakra-ui-vue/pull/536

Thanks for reporting! 🙏
