### ISSUE TITLE
Bug: ModalOverlay should close Modal on click / touch by default

### ISSUE THREAD

**Issue by codebender828** [chakra-ui/chakra-ui-vue#57]
**Describe the bug**
ModalOverlay doesn't close the Modal on click by default.

**To Reproduce**
1. Go to https://chakra-ui-vue.netlify.com/?path=/story/ui-modal--base-modal
2. Click on Show Modal button. Modal should open
3. Click the dark overlay.
4. Modal doesn't close.

**Expected behavior**
Clicking the ModalOverlay component should close Modal by default.

**Additional context**
Inspect the `ModalOverlay` component context to make sure it receives the `onClose` prop from the `$ModalContext`. Should invoke `onClose` function on click.

**Comment by koca** [comment]
Modal Overlay and Close button was not working. Fixed.

**Comment by koca** [comment]
Tested mobile(on my PR), touching overlay closed the modal.

**Comment by codebender828** [comment]
Nice work! Will be able to look at this later this evening!
