### ISSUE TITLE
@chakra-ui/nuxt module to server render emotion styles in nuxt.

### ISSUE THREAD

**Issue by codebender828** [chakra-ui/chakra-ui-vue#59]
**Is your feature request related to a problem? Please describe.**
After testing @chakra-ui/vue with Nuxt.js on various pilot projects, I've noticed that there are inconsistencies in how the [`@nuxtjs/emotion`](https://github.com/nuxt-community/emotion-module) package server-renders styles. I'm not entirely sure about what causes this because I haven't looked into it extensively.

In some cases the emotion stylesheets are correctly inlined, but after clearing the browser cache and requesting a page in a nuxt app running in universal mode, a flash of unstyled content is shown before the styles are eventually added to the DOM.

**Demo of problem:** https://chakra-nuxt.now.sh/ (Clear your browser cache before refreshing)

Further more, [`@nuxtjs/emotion`](https://github.com/nuxt-community/emotion-module) is not actively maintained, I don't entirely feel secure about the future of the project.

In order to solve these inconsistencies, something more secure needs to be built inhouse tht @chakra-ui/vue can rely on.

**Describe the solution you'd like**
The proposed solution is to create a simple nuxt module with `emotion` and `create-emotion-server` to hook into nuxt's `vue-renderer:ssr:templateParams` and `generate` hooks inline generated styles of the subject template into the final rendered HTML.

**Describe alternatives you've considered**
There really aren't any other alternatives I've found to date to fix this problem.

**Additional context**
Because of this problem, I will not be focusing on making @chakra-ui/vue stable for Nuxt SSR builds until the @chakra-ui/vue release for Vue CLI projects is stable.

We're interested in gathering more ideas and context around this problem as well as other alternative solutions!

**Comment by koca** [comment]
Yep there is an issue with the rendering. I'm guessing it compiles css on client not on server or feels like it. (check `Disable Cache` on devtools Network Panel and refresh the page)

**Comment by codebender828** [comment]
Closing issue because it seems to not to be an issue for recent nuxt projects. Unable to reproduce for now.

**Comment by agustif** [comment]
Well I can reproduce it, but I just ended up disabling ssr...
