### ISSUE TITLE
Popper: Update popper JS to latest version

### ISSUE THREAD

**Issue by codebender828** [chakra-ui/chakra-ui-vue#8]
**Is your feature request related to a problem? Please describe.**
Need to update `Popper.js` to latest version. This will reduce bundle sizes for the `Popper` component's consumers

See docs here: https://popper.js.org/

**Comment by DominusKelvin** [comment]
I'm taking this on

**Comment by codebender828** [comment]
testing git hooks

**Comment by codebender828** [comment]
will delete later

**Comment by codebender828** [comment]
the problem is tat there's a delay

**Comment by codebender828** [comment]
finally got this working. sorry guys :D deleting comments

**Comment by codebender828** [comment]
@DominusKelvin How is progress coming along with this?

**Comment by DominusKelvin** [comment]
I haven’t been able to work on it much though. Do you want to take it on @codebender828 ?

**Comment by codebender828** [comment]
Okay. Someone contacted me on Twitter hoping to work on it. I wanted to know if you were still on this so I know how to respond. Thanks. I think I can ask them to take it on, since you're currently working on docs 👍

**Comment by codebender828** [comment]
Hey. This task has changed priority, and I'm making the executive decision to take over implementing this issue to get it done quickly. Thank you so much for offering to take it on, please do take a look at the other issues in the project if you are willing! Thank you!
