### ISSUE TITLE
Prefix all injected variables with `$chakraXXX`

### ISSUE THREAD

**Issue by codebender828** [chakra-ui/chakra-ui-vue#84]
**Is your feature request related to a problem? Please describe.**
In accordance with the Vue style guide, [it is recommended to prefix all our injected variable names with a unique identifier.](https://vuejs.org/v2/style-guide/#Private-property-names-essential)

**Describe the solution you'd like**
Prefix all component injected variables with `$chakra`

This would change our injected variables from:
`$colorMode` -> `$chakraColorMode`
`$theme` -> `$chakraTheme`
`$icons` -> `$chakraIcons`

This will help with preventing namespace clashing with other authors.

**Comment by koca** [comment]
I like them as is but to prevent namespace issues, we can prefix with `chakra` 👍
