### ISSUE TITLE
Add accessibility report for all Chakra components

### ISSUE THREAD

**Issue by codebender828** [chakra-ui/chakra-ui-vue#88]
**Is your feature request related to a problem? Please describe.**
Because accessibility is a Chakra UI fundamental concept, I feel that it would be a great idea to document for consumers who answers to the following questions:

_"Huh? 😒 How is this button accessible?! Looks pretty alright to me!"_

_"Also what do you mean this modal is accessible? Hmm? How do I know it is? 🕵🏽‍♂️"_

_"I'm a Vue developer building a website for a specific group of people and I need to find a component library that supports accessibility and allows me to work fast! Can I use Chakra UI Vue for my end users?"_

This aims to describe the supported WAI-ARIA guidelines for all Chakra components. For the sake of of people who might consider accessibility as a core criterium for choosing a component library for an application, I feel that to ease the burden of inspecting the source code, we should briefly document how each component is built support accessibility.

If the Chakra component is a custom/authored component, we should use WAI-ARIA guidelines as a benchmark.

This will also a be a useful resource for developers who would like to know about authoring accessible javascript applications.

**Describe the solution you'd like**
In each Chakra component folder, we can create an `accessibility.md` file and describe the component's accessibility there. We can then link to it from the official docs for those who would like to know more.

Ideas and contributions are welcome! 😁

**Comment by codebender828** [comment]
For the record, this issue has been assigned to @saptaksengupta

**Comment by saptaksengupta** [comment]
@codebender828 I have started working on it.
