### ISSUE TITLE
How to integrate with Gridsome?

### ISSUE THREAD

**Issue by ckissi** [chakra-ui/chakra-ui-vue#92]
Can anybody provide an example how to use this with Gridsome?

**Comment by codebender828** [comment]
Hi @ckissi ! I'm sorry I haven't yet made examples yet with gridsome. But I'll add this to the roadmap over at #89 

I don't have any experience with Gridsome yet, but will be happy to look into it for you soon.

**Comment by ckissi** [comment]
Thank you so much. Waiting for it.

**Comment by codebender828** [comment]
Hey, @ckissi ! Looks like @koca Made a Gridsome starter for you for chakra-ui/vue. Awesome!

Find it on the readme for this repo or also directly here:
https://codesandbox.io/s/chakra-ui-gridsome-demo-038c9
